name: "anti_spoofing"
platform: "tensorflow_savedmodel"
name: image-classifier
platform: tensorflow_savedmodel
max_batch_size: 1
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [1, 224, 224, 3]
  }
]
output [
  {
    name: "output_1"
    data_type: TYPE_FP32
    dims: [1, 1]
  }
]